### ISSUE TITLE
Transparency != Transmission

### ISSUE THREAD

**Issue by Aranuvir** [makehumancommunity/community-plugins-makeskin#3]
IMHO the transparencyMap should go into the alpha socket, too.

**Comment by joepal1976** [comment]
The reason it is plugged into the transmission socket is because of a few reasons:

* We already have one way to achieve alpha transparency. The diffuse alpha channel is used by all current assets that need alpha transparency. Introducing another competing approach would be confusing. Also, having two nodes targeting the same input socket is cumbersone, it'd require a mix node in that case
* If we ever want to support things such as IOR in materials, we need something targeting transmission. Alpha transparency isn't influenced by IOR. 
* MakeHuman makes no use whatsoever of transparencyMap. It's defined in the material class, but it's not then used anywhere else. It is silently ignored. Reusing it for transmission type transparency does no harm.

Since I think we will want transmission type transparency at some point, the alternative I can see is defining a separate key for it. In that case the transparencymapTexture and transparencymapIntensity keys will not be used at all.

**Comment by Aranuvir** [comment]
I think the transparency map is only necessary for texture maps that cannot handle alpha channels, in particular for jpeg images. It should be "either or" not "and", if an transparency map exists the alpha channel should be ignored.

**Comment by joepal1976** [comment]
I took the easy way out and simply changed all uses of transparencymapTexture to a new key "transmissionmapTexture" for mapping against transmission.

**Comment by Aranuvir** [comment]
In that case we probably will have to update MH, too. Otherwise the information will not survive a round trip from Blender to MH and back...

**Comment by joepal1976** [comment]
MH does not need to be modified. The MHAPI plugin might need to be though. This has already been done in https://github.com/makehumancommunity/community-plugins-mhapi/commit/68884aae3f4e327119890e4f0f4f363bbf4012bc
